default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: point_sale_development
  user: point_sale_user
  password: point_sale_user

test:
  <<: *default
  database: point_sale_test
  user: point_sale_user
  password: point_sale_user

production:
  <<: *default
  database: point_sale_production
  user: point_sale_user
  password: point_sale_user
